using System.Text.Json;
using Thoth.Core.Chat;
using Thoth.Llm.Models;

namespace Thoth.Tests.Core;

public sealed class SelfContainedReasoningModelTests
{
    [Fact]
    public async Task CompleteAsync_GreetingRespondsLikeAssistant()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [new ChatMessage(ChatRole.User, "Hello")],
            "thoth-self",
            0));

        Assert.Contains("request: Hello", response.Content);
        Assert.Contains("intent: general/chat", response.Content);
        Assert.DoesNotContain("Recursive parse:", response.Content);
        Assert.DoesNotContain("Recursive self-check", response.Content);
        Assert.DoesNotContain("Hey, I am here", response.Content);
        Assert.DoesNotContain("self-contained mode", response.Content, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task CompleteAsync_CapabilityQuestionExplainsToolUse()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [new ChatMessage(ChatRole.User, "what can you do?")],
            "thoth-self",
            0));

        Assert.Contains("request: what can you do?", response.Content);
        Assert.Contains("capabilities:", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("route:", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("I can work as a local agent", response.Content, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task CompleteAsync_FinalAnswerKeepsGoalSeparateFromPlan()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Goal:
                Review the backend API endpoints and summarize them

                Plan:
                Self-contained reasoning plan generated by Thoth.

                Observations:
                Tool: file.read
                Succeeded: True
                Return a JSON plan only. Do not include markdown.
                app.MapGet("/health", () => Results.Ok());

                Write a direct, useful final answer.
                """)
            ],
            "thoth-self",
            0));

        Assert.Contains("request: Review the backend API endpoints and summarize them", response.Content);
        Assert.Contains("intent: backend/inspect", response.Content);
        Assert.Contains("GET /health", response.Content);
        Assert.DoesNotContain("Tools used:", response.Content);
        Assert.DoesNotContain("What I found:", response.Content);
        Assert.False(response.Content.StartsWith("{", StringComparison.Ordinal));
        Assert.DoesNotContain("Intent understood:\r\n- Review the backend API endpoints and summarize them    Plan:", response.Content);
    }

    [Fact]
    public async Task CompleteAsync_UnderstandingCheckGetsNaturalDirectReply()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [new ChatMessage(ChatRole.User, "\u0627\u0646\u062a \u0641\u0627\u0647\u0645\u0646\u064a")],
            "thoth-self",
            0));

        Assert.Contains("\u0637\u0644\u0628: \u0627\u0646\u062a \u0641\u0627\u0647\u0645\u0646\u064a", response.Content);
        Assert.Contains("\u0646\u064a\u0629: general/chat", response.Content);
        Assert.DoesNotContain("\u062a\u0641\u0643\u064a\u0643 recursive", response.Content);
        Assert.DoesNotContain("\u0645\u0631\u0627\u062c\u0639\u0629 recursive", response.Content);
        Assert.DoesNotContain("I read it as", response.Content);
        Assert.DoesNotContain("Detected topic", response.Content);
    }

    [Fact]
    public async Task CompleteAsync_PlanningReadsGoalFromNextLine()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Return a JSON plan only.
                Goal:
                train the local reasoning model

                Available tools:
                - memory.search
                - workspace.summary
                """)
            ],
            "thoth-self",
            0));

        Assert.Contains("train the local reasoning model", response.Content);
    }

    [Fact]
    public async Task CompleteAsync_UnderstandingDetectsModelTrainingTask()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Classify the user's message.
                User message:
                backend model is not thinking, build and train a smarter neural reasoning model
                """)
            ],
            "thoth-self",
            0));

        using var json = JsonDocument.Parse(response.Content);
        Assert.Equal("workspace_task", json.RootElement.GetProperty("intent").GetString());
        Assert.Equal("model", json.RootElement.GetProperty("topic").GetString());
        Assert.True(json.RootElement.GetProperty("requiresTools").GetBoolean());
    }

    [Theory]
    [InlineData("can you build a C# method")]
    [InlineData("\u0639\u0627\u064a\u0632\u0643 \u062a\u0639\u0645\u0644\u064a meethod in C#")]
    [InlineData("\u0641\u064a\u0646 \u0627\u0644 method \u062a\u0639\u0631\u0641 \u062a\u0639\u0645\u0644\u064a")]
    public async Task CompleteAsync_UnderstandingDetectsCodingMethodTask(string message)
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, $"""
                Classify the user's message.
                User message:
                {message}
                """)
            ],
            "thoth-self",
            0));

        using var json = JsonDocument.Parse(response.Content);
        Assert.Equal("code_generation", json.RootElement.GetProperty("intent").GetString());
        Assert.Equal("coding", json.RootElement.GetProperty("topic").GetString());
        Assert.False(json.RootElement.GetProperty("requiresTools").GetBoolean());
    }

    [Theory]
    [InlineData("add a C# method to Program.cs")]
    [InlineData("\u0636\u064a\u0641 method \u0641\u064a \u0645\u0644\u0641 Program.cs")]
    public async Task CompleteAsync_UnderstandingDetectsProjectBoundMethodTask(string message)
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, $"""
                Classify the user's message.
                User message:
                {message}
                """)
            ],
            "thoth-self",
            0));

        using var json = JsonDocument.Parse(response.Content);
        Assert.Equal("workspace_task", json.RootElement.GetProperty("intent").GetString());
        Assert.Equal("backend", json.RootElement.GetProperty("topic").GetString());
        Assert.True(json.RootElement.GetProperty("requiresTools").GetBoolean());
    }

    [Fact]
    public async Task CompleteAsync_GenericArabicMethodRequestReturnsCodePromptNotRouteMap()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [new ChatMessage(ChatRole.User, "\u0639\u0627\u064a\u0632\u0643 \u062a\u0639\u0645\u0644\u064a meethod in C#")],
            "thoth-self",
            0));

        Assert.Contains("contract:", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("validation", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("\u0645\u0631\u0627\u062c\u0639\u0629 recursive", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("```csharp", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("public static", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("HTTP routes", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("\u0641\u062d\u0635\u062a \u0645\u062d\u0644\u064a\u0627", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("route map", response.Content, StringComparison.OrdinalIgnoreCase);
    }

    [Theory]
    [InlineData("Hello")]
    [InlineData("\u0627\u0646\u062a \u0641\u0627\u0647\u0645\u0646\u064a")]
    public async Task CompleteAsync_UnderstandingKeepsCasualChatOutOfTools(string message)
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, $"""
                Classify the user's message.
                User message:
                {message}
                """)
            ],
            "thoth-self",
            0));

        using var json = JsonDocument.Parse(response.Content);
        Assert.Equal("general_chat", json.RootElement.GetProperty("intent").GetString());
        Assert.Equal("general", json.RootElement.GetProperty("topic").GetString());
        Assert.False(json.RootElement.GetProperty("requiresTools").GetBoolean());
    }

    [Fact]
    public async Task CompleteAsync_UnderstandingDetectsWebResearch()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Classify the user's message.
                User message:
                search the web for LangGraph and summarize it
                """)
            ],
            "thoth-self",
            0));

        using var json = JsonDocument.Parse(response.Content);
        Assert.Equal("research", json.RootElement.GetProperty("intent").GetString());
        Assert.Equal("research", json.RootElement.GetProperty("topic").GetString());
        Assert.True(json.RootElement.GetProperty("requiresTools").GetBoolean());
    }

    [Fact]
    public async Task CompleteAsync_PlanningUsesWebResearchForExternalQuestions()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Return a JSON plan only.
                Goal:
                search the web for open source ai agents and summarize them

                Available tools:
                - memory.search
                - web.research
                - workspace.summary
                """)
            ],
            "thoth-self",
            0));

        Assert.Contains("web.research", response.Content);
        Assert.DoesNotContain("workspace.summary", response.Content);
        Assert.DoesNotContain("workspace.map", response.Content);
    }

    [Fact]
    public async Task CompleteAsync_FinalResearchAnswerPrefersWebEvidenceOverMemoryNoise()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Goal:
                search the web for LangGraph and summarize it

                Observations:
                Tool: web.research
                Succeeded: True
                Research query: LangGraph
                Search results:
                Source: Bing HTML
                1. LangGraph docs
                   URL: https://langchain-ai.github.io/langgraph/
                   Snippet: LangGraph helps build stateful agents with graph workflows.
                Read summaries:
                Source 1: LangGraph docs
                URL: https://langchain-ai.github.io/langgraph/
                - LangGraph supports durable, stateful agent workflows.
                Tool: memory.search
                Succeeded: True
                old project memory about workspace.summary and file.search

                Write a direct final answer.
                """)
            ],
            "thoth-self",
            0));

        Assert.Contains("https://langchain-ai.github.io/langgraph/", response.Content);
        Assert.Contains("LangGraph", response.Content);
        Assert.Contains("tools: web.research", response.Content);
        Assert.DoesNotContain("Recursive answer check", response.Content);
        Assert.DoesNotContain("old project memory", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("workspace.summary", response.Content, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task CompleteAsync_GenericArabicMethodReplyDoesNotContainMojibake()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [new ChatMessage(ChatRole.User, "\u0639\u0627\u064a\u0632\u0643 \u062a\u0639\u0645\u0644\u064a meethod in C#")],
            "thoth-self",
            0));

        Assert.Contains("contract:", response.Content);
        Assert.DoesNotContain("\u062a\u0641\u0643\u064a\u0643 recursive", response.Content);
        Assert.DoesNotContain("Ø", response.Content);
        Assert.DoesNotContain("Ù", response.Content);
    }

    [Fact]
    public async Task CompleteAsync_AgentDecisionPromptChoosesMemoryBeforeWorkspaceInspection()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Return one JSON agent decision only; no markdown and no hidden chain-of-thought.
                Tool action: {"kind":"tool","rationale":"short observable reason","tool":"name","arguments":{"key":"value"}}
                Final action: {"kind":"final","rationale":"short reason","answer":"direct final answer"}

                Goal: the model is not thinking, build a real reasoning brain
                Workspace: C:\repo
                Dry run: False

                Tools:
                - memory.search: Searches memory. (query:string required)
                - workspace.summary: Summarizes workspace. (maxEntries:integer)
                - workspace.map: Builds workspace map. (maxDepth:integer)
                - file.read: Reads file. (path:string required)

                Executed observations:
                - none

                Rules: inspect before editing.
                """)
            ],
            "thoth-self",
            0));

        using var json = JsonDocument.Parse(response.Content);
        Assert.Equal("tool", json.RootElement.GetProperty("kind").GetString());
        Assert.Equal("memory.search", json.RootElement.GetProperty("tool").GetString());
    }

    [Fact]
    public async Task CompleteAsync_AgentDecisionPromptReadsReasoningBrainFiles()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Return one JSON agent decision only; no markdown and no hidden chain-of-thought.
                Tool action: {"kind":"tool","rationale":"short observable reason","tool":"name","arguments":{"key":"value"}}
                Final action: {"kind":"final","rationale":"short reason","answer":"direct final answer"}

                Goal: the model is not thinking, build a real reasoning brain
                Workspace: C:\repo
                Dry run: False

                Tools:
                - memory.search: Searches memory. (query:string required)
                - workspace.summary: Summarizes workspace. (maxEntries:integer)
                - workspace.map: Builds workspace map. (maxDepth:integer)
                - file.read: Reads file. (path:string required)

                Executed observations:
                - Step 1: Recall relevant project memory before choosing local evidence.
                  Tool: memory.search {"query":"the model is not thinking, build a real reasoning brain","limit":"6"}
                  Success: True
                  Observation: no memory
                - Step 2: Build a workspace-level frame before inspecting files.
                  Tool: workspace.summary {"maxEntries":"80"}
                  Success: True
                  Observation: solution contains Thoth.Llm and Thoth.Core
                - Step 3: Map the project so the next read is targeted.
                  Tool: workspace.map {"maxDepth":"5","maxEntries":"280"}
                  Success: True
                  Observation: src/Thoth.Llm/Models/SelfContainedReasoningModel.cs

                Rules: inspect before editing.
                """)
            ],
            "thoth-self",
            0));

        using var json = JsonDocument.Parse(response.Content);
        Assert.Equal("tool", json.RootElement.GetProperty("kind").GetString());
        Assert.Equal("file.read", json.RootElement.GetProperty("tool").GetString());
        Assert.Equal(
            "src/Thoth.Llm/Models/SelfContainedReasoningModel.cs",
            json.RootElement.GetProperty("arguments").GetProperty("path").GetString());
    }

    [Fact]
    public async Task CompleteAsync_FinalAnswerDoesNotTreatObservedDecisionPromptAsControlPrompt()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.System, "You are Thoth. Answer from evidence."),
                new ChatMessage(ChatRole.User, """
                Goal:
                inspect the decision service

                Observations:
                Step 1: Read model decision file.
                Tool: file.read {"path":"src/Thoth.Core/Agent/ModelAgentDecisionService.cs"}
                Succeeded: True
                builder.AppendLine("Return one JSON agent decision only; no markdown and no hidden chain-of-thought.");

                Write a direct final answer.
                """)
            ],
            "thoth-self",
            0));

        Assert.False(response.Content.TrimStart().StartsWith("{", StringComparison.Ordinal));
        Assert.Contains("request: inspect the decision service", response.Content);
        Assert.DoesNotContain("What I understood:", response.Content);
    }
}
