using System.Text.Json;
using Thoth.Core.Chat;
using Thoth.Llm.Models;

namespace Thoth.Tests.Core;

public sealed class SelfContainedReasoningModelTests
{
    [Fact]
    public async Task CompleteAsync_GreetingRespondsLikeAssistant()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [new ChatMessage(ChatRole.User, "Hello")],
            "thoth-self",
            0));

        Assert.Contains("Hey", response.Content);
        Assert.DoesNotContain("self-contained mode", response.Content, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task CompleteAsync_CapabilityQuestionExplainsToolUse()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [new ChatMessage(ChatRole.User, "what can you do?")],
            "thoth-self",
            0));

        Assert.Contains("workspace inspection", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("tools", response.Content, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task CompleteAsync_FinalAnswerKeepsGoalSeparateFromPlan()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Goal:
                Review the backend API endpoints and summarize them

                Plan:
                Self-contained reasoning plan generated by Thoth.

                Observations:
                Tool: file.read
                Succeeded: True
                Return a JSON plan only. Do not include markdown.
                app.MapGet("/health", () => Results.Ok());

                Write a direct, useful final answer.
                """)
            ],
            "thoth-self",
            0));

        Assert.Contains("You asked: Review the backend API endpoints and summarize them", response.Content);
        Assert.Contains("What I found:", response.Content);
        Assert.Contains("GET /health", response.Content);
        Assert.DoesNotContain("Tools used:", response.Content);
        Assert.False(response.Content.StartsWith("{", StringComparison.Ordinal));
        Assert.DoesNotContain("Intent understood:\r\n- Review the backend API endpoints and summarize them    Plan:", response.Content);
    }

    [Fact]
    public async Task CompleteAsync_UnderstandingCheckGetsNaturalDirectReply()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [new ChatMessage(ChatRole.User, "\u0627\u0646\u062a \u0641\u0627\u0647\u0645\u0646\u064a")],
            "thoth-self",
            0));

        Assert.Contains("\u0641\u0627\u0647\u0645\u0643", response.Content);
        Assert.DoesNotContain("I read it as", response.Content);
        Assert.DoesNotContain("Detected topic", response.Content);
    }

    [Fact]
    public async Task CompleteAsync_PlanningReadsGoalFromNextLine()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Return a JSON plan only.
                Goal:
                train the local reasoning model

                Available tools:
                - memory.search
                - workspace.summary
                """)
            ],
            "thoth-self",
            0));

        Assert.Contains("train the local reasoning model", response.Content);
    }

    [Fact]
    public async Task CompleteAsync_UnderstandingDetectsModelTrainingTask()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Classify the user's message.
                User message:
                backend model is not thinking, build and train a smarter neural reasoning model
                """)
            ],
            "thoth-self",
            0));

        using var json = JsonDocument.Parse(response.Content);
        Assert.Equal("workspace_task", json.RootElement.GetProperty("intent").GetString());
        Assert.Equal("model", json.RootElement.GetProperty("topic").GetString());
        Assert.True(json.RootElement.GetProperty("requiresTools").GetBoolean());
    }

    [Theory]
    [InlineData("Hello")]
    [InlineData("\u0627\u0646\u062a \u0641\u0627\u0647\u0645\u0646\u064a")]
    public async Task CompleteAsync_UnderstandingKeepsCasualChatOutOfTools(string message)
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, $"""
                Classify the user's message.
                User message:
                {message}
                """)
            ],
            "thoth-self",
            0));

        using var json = JsonDocument.Parse(response.Content);
        Assert.Equal("general_chat", json.RootElement.GetProperty("intent").GetString());
        Assert.Equal("general", json.RootElement.GetProperty("topic").GetString());
        Assert.False(json.RootElement.GetProperty("requiresTools").GetBoolean());
    }
}
