using Thoth.Core.Chat;
using Thoth.Llm.Models;

namespace Thoth.Tests.Core;

public sealed class SelfContainedReasoningModelTests
{
    [Fact]
    public async Task CompleteAsync_GreetingRespondsLikeAssistant()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [new ChatMessage(ChatRole.User, "Hello")],
            "thoth-self",
            0));

        Assert.Contains("Hey", response.Content);
        Assert.DoesNotContain("self-contained mode", response.Content, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task CompleteAsync_CapabilityQuestionExplainsToolUse()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [new ChatMessage(ChatRole.User, "what can you do?")],
            "thoth-self",
            0));

        Assert.Contains("workspace inspection", response.Content, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("tools", response.Content, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task CompleteAsync_FinalAnswerKeepsGoalSeparateFromPlan()
    {
        var model = new SelfContainedReasoningModel();

        var response = await model.CompleteAsync(new ChatRequest(
            [
                new ChatMessage(ChatRole.User, """
                Goal:
                Review the backend API endpoints and summarize them

                Plan:
                Self-contained reasoning plan generated by Thoth.

                Observations:
                Tool: file.read
                Succeeded: True
                app.MapGet("/health", () => Results.Ok());

                Write a direct, useful final answer.
                """)
            ],
            "thoth-self",
            0));

        Assert.Contains("- Review the backend API endpoints and summarize them", response.Content);
        Assert.DoesNotContain("Intent understood:\r\n- Review the backend API endpoints and summarize them    Plan:", response.Content);
    }
}
